### ISSUE TITLE
Best way to Feedback 

### ISSUE THREAD

**Issue by liach** [Glavo/classfile#1]
Just want to comment that there's classfile-api-dev@openjdk.org https://mail.openjdk.org/pipermail/classfile-api-dev/ mailing list, which is good for feedback.

In addition, classfile api works better with preview features like pattern matching in switch, which is the basis of the transform model.

**Comment by Glavo** [comment]
> Just want to comment that there's [classfile-api-dev@openjdk.org](mailto:classfile-api-dev@openjdk.org) https://mail.openjdk.org/pipermail/classfile-api-dev/ mailing list, which is good for feedback.

Thanks for letting me know about this mailing list.

> In addition, classfile api works better with preview features like pattern matching in switch, which is the basis of the transform model.

Yes, I'm thinking of adding some description to help users.

I thought I might add a suggestion about using [jabel](https://github.com/bsideup/jabel) so users can use the latest language features but still target Java 17's bytecode.

**Comment by liach** [comment]
On a side note, now on the JBS there is a classfile-api label https://bugs.openjdk.org/browse/JDK-8307326?jql=labels%20%3D%20classfile-api that Class-File API issues are grouped under.
