### ISSUE TITLE
Re-porting Class-File API

### ISSUE THREAD

**Issue by Glavo** [Glavo/classfile#14]
Class-File API is transitioning to preview (https://github.com/openjdk/jdk/pull/15706). When they are done, I will update this project to sync with upstream.

**Comment by Rongmario** [comment]
Any updates?

**Comment by Glavo** [comment]
> Any updates?

I've been busy with other projects lately, so I'll take some time to work on this next month.

**Comment by Rongmario** [comment]
Sounds good to me!

**Comment by ice1000** [comment]
https://github.com/openjdk/jdk/pull/15706 is merged!

**Comment by ice1000** [comment]
Then there goes https://github.com/openjdk/jdk/pull/16947
Then https://github.com/openjdk/jdk/pull/16505 and https://git.openjdk.org/jdk/pull/17051

**Comment by Glavo** [comment]
#15
